
## Introduction

### About the course 

The course introduces some basic statistical analysis methods and open research tools to analyze data, and to document and share code and results. The course consists of seven weekly meetings with the following topics:\

* Start me up!
* Regression and model validation
* Logistic regression
* Clustering and classification
* Dimensionality reduction techniques
* Analysis of longitudinal data
* Kimmo's textbook, special edition

The course is organized __online__ and is organized by __Doctoral School in Humanities and Social Sciences__.

### About me

I'm a PhD student in the University of Helsinki and the topic of my PhD thesis is Projections of Population Health Outcomes. I'm working at the Finnish Institute for Health and Welfare (THL) as a statistical researcher. I currently have a busy schedule but I was happy to squeeze this course into it although my supervisor told me about this course already a few years ago. I'm looking forward for participating in IODS and getting an overview about the tools used for documenting and sharing R-code.\

The link to my [__GitHub repository__](https://github.com/kontto/IODS-project).\
